### ISSUE TITLE
Realtime Audiosection of Mac

### ISSUE THREAD

**Issue by tjingboem** [csound/manual#11]
i think the section Real-Time Audio, that starts here: http://csound.github.io/docs/manual/UsingRealTime.html
can be reorganized: under the heading "Using Csound" there is only talk about "Realtime I/O on Linux", while the next page shows "Windows Real-Time Audio". And even one page further there is talk about Realtime Audio for the Mac, but for a long time i read the words: Coming Soon...  :)

Is it not better to change all this into a chapter "Realtime I/O", so Audio and Midi, and then talk about: On Linux, On Windows, On the Mac? 
I do not have a Mac, i have no idea if something has to be said about Realtime I/O on a Mac.

**Comment by tjingboem** [comment]
sorry, forgot to mention to include the next page after the Mac: Optimizing Audio I/O Latency under Using Csound

**Comment by vlazzarini** [comment]
That sounds good to me.

**Comment by tjingboem** [comment]
i do not know how to take the information on Linux on the http://csound.github.io/docs/manual/RealTimeWindows.html, create a new page that should be in between http://csound.github.io/docs/manual/UsingRealTime.html and http://csound.github.io/docs/manual/RealTimeWindows.html.
Can someone create such a new page for me?

**Comment by fggp** [comment]
Hi Menno,

this page already exists in the overview folder: realtimelinux.xml.
It was not displayed on its own html page due to a layout mistake in the
overview/using.xml page. Corrected now. So if you build the manual,
realtimelinux will be placed on its own html page.

Regards

Francois

2015-05-08 20:57 GMT+02:00 Menno <notifications@github.com>:

**Comment by tjingboem** [comment]
Thanks, Francois, for correcting this. I saw realtimelinux.xml, but i did not understand why this page was not created. Makes more sense now.

Next step would be to add the Midi Sequencer driver section for Linux ( i can give it a try) and some nice words on the Mac page.

I do not have a Mac. Perhaps somebody else can add some text to this section?

**Comment by fggp** [comment]
Did move Optimizing Audio I/O Latency in a new file: overview/optimizinglatency.xml, and modified the layout so that it is placed after the page about Realtime Audio for the Mac.

**Comment by tjingboem** [comment]
this is partially solved, will file a new issue about the Mac Realtime Audiosection
